DepartmentOfHealth-htbhf/htbhf-claimant-service

api/src/test/java/uk/gov/dhsc/htbhf/claimant/assertion/ConstraintViolationAssert.java, api/src/test/java/uk/gov/dhsc/htbhf/claimant/entity/ClaimantTest.java, api/src/test/java/uk/gov/dhsc/htbhf/claimant/testsupport/ClaimDTOTestDataFactory.java, api/src/test/java/uk/gov/dhsc/htbhf/claimant/testsupport/ClaimantTestDataFactory.java, config/pmd/test-rulesets.xml
Also required disabling a few PMD rules for tests only.
=> Create custom AssertJ Assertion class for easily making validation assertions

api/src/main/java/uk/gov/dhsc/htbhf/claimant/ApiDocumentation.java, api/src/main/resources/application.yml, manifest.yml
Also added logging of application info at startup, and tidied up application.yml
=> HTBHF-541 added variable-service as a service in manifest.yml

api/src/main/java/uk/gov/dhsc/htbhf/claimant/exception/EligibilityClientException.java, api/src/main/java/uk/gov/dhsc/htbhf/claimant/service/ClaimService.java, api/src/main/java/uk/gov/dhsc/htbhf/claimant/service/EligibilityClient.java, api/src/test/java/uk/gov/dhsc/htbhf/claimant/service/ClaimServiceTest.java, api/src/test/java/uk/gov/dhsc/htbhf/claimant/service/EligibilityClientTest.java
- Handle rest exceptions in eligibility client
- Ensure claimant is always saved, even on exceptions
=> HTBHF-679 Handle rest exceptions in eligibility client

.gitmodules
This should stop us getting the detached HEAD situation.
=> [NO_JIRA] Fix branch on config sub-module.

api/src/main/java/uk/gov/dhsc/htbhf/claimant/entitlement/EntitlementCalculator.java, api/src/main/java/uk/gov/dhsc/htbhf/claimant/entitlement/PregnancyEntitlementCalculator.java, api/src/main/java/uk/gov/dhsc/htbhf/claimant/entitlement/VoucherEntitlement.java, api/src/main/resources/application.yml, api/src/test/java/uk/gov/dhsc/htbhf/claimant/entitlement/EntitlementCalculatorTest.java, api/src/test/java/uk/gov/dhsc/htbhf/claimant/entitlement/PregnancyEntitlementCalculatorTest.java, api/src/test/java/uk/gov/dhsc/htbhf/claimant/entitlement/VoucherEntitlementTest.java, api/src/test/resources/application.yml
- Move entitlement calculators to entitlement package
- Create voucher entitlement class
- Update entitlement calculator to return a voucher entitlement object instead of just the voucher entitlement total
=> HTBHF-926 construct entitlement object in entitlement calculator

api/src/main/java/uk/gov/dhsc/htbhf/claimant/controller/ClaimController.java, api/src/main/java/uk/gov/dhsc/htbhf/claimant/converter/VoucherEntitlementToDTOConverter.java, api/src/main/java/uk/gov/dhsc/htbhf/claimant/model/ClaimResponse.java, api/src/main/java/uk/gov/dhsc/htbhf/claimant/model/ClaimResultDTO.java, api/src/main/java/uk/gov/dhsc/htbhf/claimant/model/VoucherEntitlementDTO.java, api/src/main/java/uk/gov/dhsc/htbhf/claimant/service/ClaimResult.java, api/src/main/java/uk/gov/dhsc/htbhf/claimant/service/NewClaimService.java, api/src/test/java/uk/gov/dhsc/htbhf/claimant/ClaimantServiceIntegrationTests.java, api/src/test/java/uk/gov/dhsc/htbhf/claimant/controller/ClaimControllerTest.java, api/src/test/java/uk/gov/dhsc/htbhf/claimant/service/NewClaimServiceTest.java, api/src/test/java/uk/gov/dhsc/htbhf/claimant/testsupport/ClaimDTOTestDataFactory.java, api/src/test/java/uk/gov/dhsc/htbhf/claimant/testsupport/ClaimResponseTestDataFactory.java, api/src/test/java/uk/gov/dhsc/htbhf/claimant/testsupport/ClaimResultDTOTestDataFactory.java, api/src/test/java/uk/gov/dhsc/htbhf/claimant/testsupport/EligibilityResponseTestDataFactory.java, api/src/test/java/uk/gov/dhsc/htbhf/claimant/testsupport/TestConstants.java, api/src/test/java/uk/gov/dhsc/htbhf/claimant/testsupport/VoucherEntitlementDTOTestDataFactory.java, api/src/test/java/uk/gov/dhsc/htbhf/claimant/testsupport/VoucherEntitlementTestDataFactory.java, swagger.yml
- Create voucher entitlement
- Add voucher entitlement to claim service response for all ELIGIBLE claims
=> HTBHF-926 Add voucher entitlement to claim response

api/src/main/java/uk/gov/dhsc/htbhf/claimant/message/context/DetermineEntitlementMessageContext.java, api/src/main/java/uk/gov/dhsc/htbhf/claimant/message/context/MakePaymentMessageContext.java, api/src/main/java/uk/gov/dhsc/htbhf/claimant/message/context/MessageContextLoader.java, api/src/test/java/uk/gov/dhsc/htbhf/claimant/message/context/MessageContextLoaderTest.java
I.e. to create MakePaymentMessageContexts as well.
=> HTBHF-1289 Refactored MessageContextLoader to be more generic

api/build.gradle, smoke_tests/build.gradle
Updating spring boot version to fix synk vulnerability.
=> NOJIRA Updating spring boot version to fix vulnerabilities.

api/src/main/java/uk/gov/dhsc/htbhf/claimant/message/MessagePayloadFactory.java, api/src/main/java/uk/gov/dhsc/htbhf/claimant/message/processor/NewCardMessageProcessor.java, api/src/test/java/uk/gov/dhsc/htbhf/claimant/message/EmailPayloadAssertions.java, api/src/test/java/uk/gov/dhsc/htbhf/claimant/message/MessagePayloadFactoryTest.java, api/src/test/java/uk/gov/dhsc/htbhf/claimant/message/processor/NewCardMessageProcessorTest.java
- Plug in email being sent after the new card creation has completed successfully.
- Fix carriage return display issue in email.
- Refactor out common email payload assertions into utility class.
=> HTBHF-1883 Trigger email being sent after card creation has completed.

api/src/main/java/uk/gov/dhsc/htbhf/claimant/entity/Address.java, api/src/test/java/uk/gov/dhsc/htbhf/claimant/entity/AddressTest.java, api/src/test/java/uk/gov/dhsc/htbhf/claimant/testsupport/AddressTestDataFactory.java, db/src/main/resources/db/migration/V1_036__add_county_to_address.sql
Added county to address table. Defaults to UK as is required by AllPay but actual county doesn't matter.
=> HTBHF-1915 Added county field to address. Defaults to UK.

api/src/main/java/uk/gov/dhsc/htbhf/claimant/converter/ClaimantDTOToClaimantConverter.java, api/src/test/java/uk/gov/dhsc/htbhf/claimant/converter/ClaimantDTOToClaimantConverterTest.java, db/src/main/resources/db/migration/V1_037__uppercase_nino.sql
Nasty potential bug that slipped through the net. Spotted when listing NINOs in the development db.
=> HTBHF-2171 Ensured NINO is always uppercase

api/src/main/java/uk/gov/dhsc/htbhf/claimant/entitlement/BackDatedPaymentCycleEntitlementCalculator.java, api/src/main/java/uk/gov/dhsc/htbhf/claimant/entitlement/PaymentCycleEntitlementCalculator.java, api/src/main/java/uk/gov/dhsc/htbhf/claimant/message/processor/ChildDateOfBirthCalculator.java, api/src/main/java/uk/gov/dhsc/htbhf/claimant/service/EligibilityAndEntitlementService.java, api/src/test/java/uk/gov/dhsc/htbhf/claimant/entitlement/BackDatedPaymentCycleEntitlementCalculatorTest.java, api/src/test/java/uk/gov/dhsc/htbhf/claimant/entitlement/PaymentCycleEntitlementCalculatorIntegrationTests.java, api/src/test/java/uk/gov/dhsc/htbhf/claimant/entitlement/PaymentCycleEntitlementCalculatorTest.java, api/src/test/java/uk/gov/dhsc/htbhf/claimant/message/processor/ChildDateOfBirthCalculatorTest.java, api/src/test/java/uk/gov/dhsc/htbhf/claimant/service/EligibilityAndEntitlementServiceTest.java
Tidying up a TODO from the last PR where we needed to rename the CycleEntitleCalculator and a number of related classes. Nothing more than renames in this PR.
=> HTBHF-2288 Rename CycleEntitleCalculator class and related classes.

api/src/test/java/uk/gov/dhsc/htbhf/claimant/ClaimantServiceAssertionUtils.java, api/src/test/java/uk/gov/dhsc/htbhf/claimant/ClaimantServiceIntegrationTestsWithMocks.java, api/src/test/java/uk/gov/dhsc/htbhf/claimant/ClaimantServiceIntegrationTestsWithoutMocks.java, api/src/test/java/uk/gov/dhsc/htbhf/claimant/PaymentCycleIntegrationTests.java, api/src/test/java/uk/gov/dhsc/htbhf/claimant/testsupport/CardRequestTestDataFactory.java, api/src/test/java/uk/gov/dhsc/htbhf/claimant/testsupport/CardResponseTestDataFactory.java, api/src/test/java/uk/gov/dhsc/htbhf/claimant/testsupport/RepositoryMediator.java, api/src/test/java/uk/gov/dhsc/htbhf/claimant/testsupport/WiremockManager.java
This test has uncovered a bug, so it is disabled for now
=> HTBHF-2325 Added an integration test that confirms the new card request, deposit funds and welcome email are sent correctly

api/src/main/java/uk/gov/dhsc/htbhf/claimant/message/payload/EmailType.java, api/src/main/java/uk/gov/dhsc/htbhf/claimant/message/processor/PaymentCycleEmailHandler.java, api/src/test/java/uk/gov/dhsc/htbhf/claimant/message/processor/PaymentCycleEmailHandlerTest.java, api/src/test/java/uk/gov/dhsc/htbhf/claimant/testsupport/PaymentCycleVoucherEntitlementTestDataFactory.java
Sending email notification when a child turns one in the next cycle.
=> HTBHF-1658 Sending email notification when a child turns one in the next cycle.

api/src/main/java/uk/gov/dhsc/htbhf/claimant/repository/ClaimRepository.java, api/src/main/java/uk/gov/dhsc/htbhf/claimant/service/ClaimService.java, api/src/test/java/uk/gov/dhsc/htbhf/claimant/repository/ClaimRepositoryTest.java, api/src/test/java/uk/gov/dhsc/htbhf/claimant/service/ClaimServiceTest.java, api/src/test/java/uk/gov/dhsc/htbhf/claimant/testsupport/RepositoryMediator.java
This is a step towards reducing the size of the ClaimService, which has too many methods
=> HTBHF-2412 refactor findClaim method out to claimRepository

api/src/main/java/uk/gov/dhsc/htbhf/claimant/communications/EmailMessagePayloadFactory.java
Overloaded buildEmailMessagePayload and createCommonEmailPersonalisationMap to allow email payloads to be created without a PaymentCycle.
=> HTBHF-2582 Refactored EmailMessagePayloadFactory

api/src/main/java/uk/gov/dhsc/htbhf/claimant/repository/ClaimRepository.java, api/src/main/java/uk/gov/dhsc/htbhf/claimant/service/v1/EligibilityAndEntitlementServiceV1.java, api/src/test/java/uk/gov/dhsc/htbhf/claimant/repository/ClaimRepositoryTest.java, api/src/test/java/uk/gov/dhsc/htbhf/claimant/service/v1/EligibilityAndEntitlementServiceV1Test.java
Refactoring this out so that the v2 service can use the same code.
=> HTBHF-2570 Create default method for finding a single NINO match for the claim.

api/src/main/java/uk/gov/dhsc/htbhf/claimant/entitlement/PaymentCycleEntitlementCalculator.java, api/src/main/java/uk/gov/dhsc/htbhf/claimant/service/v2/EligibilityAndEntitlementServiceV2.java, api/src/main/java/uk/gov/dhsc/htbhf/claimant/service/v2/EligibilityClientV2.java, api/src/test/java/uk/gov/dhsc/htbhf/claimant/service/v2/EligibilityAndEntitlementServiceV2Test.java
This currently isn't used anywhere, will be manually wired into the v2 controller once that controller has been created.
=> HTBHF-2570 Create v2 of EligibilityAndEntitlementService and test.

api/src/main/java/uk/gov/dhsc/htbhf/claimant/service/v2/EligibilityAndEntitlementServiceV2.java, api/src/main/java/uk/gov/dhsc/htbhf/claimant/service/v3/EligibilityAndEntitlementServiceV3.java, api/src/main/java/uk/gov/dhsc/htbhf/claimant/service/v3/EligibilityClientV3.java, api/src/test/java/uk/gov/dhsc/htbhf/claimant/service/v2/EligibilityAndEntitlementServiceV2Test.java, api/src/test/java/uk/gov/dhsc/htbhf/claimant/service/v3/EligibilityAndEntitlementServiceV3Test.java, api/src/test/java/uk/gov/dhsc/htbhf/claimant/service/v3/EligibilityClientV3Test.java
Second part of the rename of v1->v2 and v2->v3. After this we can now go ahead and create the v3 controller.
=> HTBHF-2571 Move v1 classes to v2 and v2 classes to v3.

api/src/test/java/uk/gov/dhsc/htbhf/claimant/PaymentCycleIntegrationTests.java
Enabling tests for previously closed story.
=> HTBHF-1296 Enabled disabled tests.

api/src/main/java/uk/gov/dhsc/htbhf/claimant/message/context/MessageContextLoader.java, api/src/main/java/uk/gov/dhsc/htbhf/claimant/message/context/ReportPaymentMessageContext.java, api/src/main/java/uk/gov/dhsc/htbhf/claimant/message/payload/ReportPaymentMessagePayload.java, api/src/main/java/uk/gov/dhsc/htbhf/claimant/reporting/ReportPaymentMessageSender.java, api/src/main/java/uk/gov/dhsc/htbhf/claimant/reporting/payload/ReportPaymentPropertiesFactory.java, api/src/test/java/uk/gov/dhsc/htbhf/claimant/message/context/MessageContextLoaderTest.java, api/src/test/java/uk/gov/dhsc/htbhf/claimant/reporting/ReportPaymentMessageSenderTest.java, api/src/test/java/uk/gov/dhsc/htbhf/claimant/reporting/payload/ReportPaymentPropertiesFactoryTest.java, swagger.yml
Fixing a bug where report payment amounts were not including backdated voucher payments.
=> HTBHF-2525 Updated report a payment to include back dated vouchers.

api/src/main/java/uk/gov/dhsc/htbhf/claimant/service/claim/ClaimService.java, api/src/test/java/uk/gov/dhsc/htbhf/claimant/ClaimantLifecycleIntegrationTests.java, api/src/test/java/uk/gov/dhsc/htbhf/claimant/ClaimantServiceIntegrationTestsWithScheduledServices.java, api/src/test/java/uk/gov/dhsc/htbhf/claimant/ScheduledServiceIntegrationTest.java, api/src/test/java/uk/gov/dhsc/htbhf/claimant/service/claim/ClaimServiceTest.java, api/src/test/java/uk/gov/dhsc/htbhf/claimant/testsupport/VerificationResultTestDataFactory.java
This won't pass until the latest change to java-common is merged
=> AFHS-388 Sending we'll let you know email for successful claim whose email or phone mismatches

api/src/main/java/uk/gov/dhsc/htbhf/claimant/message/payload/LetterType.java, api/src/main/java/uk/gov/dhsc/htbhf/claimant/service/ClaimMessageSender.java, api/src/main/java/uk/gov/dhsc/htbhf/claimant/service/claim/ClaimService.java, api/src/test/java/uk/gov/dhsc/htbhf/claimant/ClaimantServiceIntegrationTestsWithScheduledServices.java, api/src/test/java/uk/gov/dhsc/htbhf/claimant/service/ClaimMessageSenderTest.java, api/src/test/java/uk/gov/dhsc/htbhf/claimant/service/claim/ClaimServiceTest.java, api/src/test/java/uk/gov/dhsc/htbhf/claimant/testsupport/ClaimantTestDataFactory.java
One of two different letters is sent depending on whether or not the benefit agency has all of the children's dob declared by the claimant.
=> AFGS-525 Sending a letter when the claimant's phone or email mismatches.

api/src/main/java/uk/gov/dhsc/htbhf/claimant/reporting/ReportPaymentMessageSender.java, api/src/main/java/uk/gov/dhsc/htbhf/claimant/service/payments/PaymentService.java, api/src/test/java/uk/gov/dhsc/htbhf/claimant/ReportPaymentIntegrationTest.java, api/src/test/java/uk/gov/dhsc/htbhf/claimant/reporting/ReportPaymentMessageSenderTest.java, api/src/test/java/uk/gov/dhsc/htbhf/claimant/service/payments/PaymentServiceTest.java
This is a precursor to future work which benefits from their being a single report payment message.
=> AFGS-405 Refactored report payment methods into one.

api/build.gradle, api/src/main/java/uk/gov/dhsc/htbhf/claimant/converter/ClaimToClaimDTOConverter.java, api/src/main/java/uk/gov/dhsc/htbhf/claimant/entity/Claim.java, api/src/main/java/uk/gov/dhsc/htbhf/claimant/model/ClaimDTO.java, api/src/main/java/uk/gov/dhsc/htbhf/claimant/repository/ClaimRepository.java, api/src/main/java/uk/gov/dhsc/htbhf/claimant/service/claim/ClaimService.java, api/src/main/resources/application.yml, api/src/test/java/uk/gov/dhsc/htbhf/claimant/converter/ClaimToClaimDTOConverterTest.java, api/src/test/java/uk/gov/dhsc/htbhf/claimant/entity/ClaimTest.java, api/src/test/java/uk/gov/dhsc/htbhf/claimant/repository/ClaimRepositoryTest.java, api/src/test/java/uk/gov/dhsc/htbhf/claimant/repository/PaymentCycleRepositoryTest.java, api/src/test/java/uk/gov/dhsc/htbhf/claimant/service/claim/ClaimServiceTest.java, api/src/test/java/uk/gov/dhsc/htbhf/claimant/testsupport/ClaimTestDataFactory.java, api/src/test/java/uk/gov/dhsc/htbhf/claimant/testsupport/TestConstants.java, db/src/main/resources/db/migration/V1_063__add _reference_column_in_claim.sql, swagger.yml
logic is implemented in ClaimService to  pass unique reference for each claim
=> AFHS-2019 - added reference field in Claim, dto, converter and 
